version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - foodgram_database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: damarkevich/foodgram_backend:latest
    restart: always
    volumes:
      - foodgram_static:/backend/static/
      - foodgram_media:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: damarkevich/foodgram_frontend:latest
    volumes:
      - ../frontend/:/frontend/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/static_backend/
      - foodgram_media:/var/html/media/
    depends_on:
      - frontend

volumes:
  foodgram_database:
  foodgram_static:
  foodgram_media:
