# Generated by Django 2.2.28 on 2023-03-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeandingredient',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
