# Generated by Django 2.2.28 on 2023-04-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_add_ingredients'),
        ('recipes', '0002_auto_20230401_1417'),
    ]

    operations = [
    ]
