# Generated by Django 2.2.28 on 2023-02-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Mark is subscribed', verbose_name='Is subscribed'),
        ),
    ]
